### ISSUE TITLE
Failure of opening connection closes connection with conn_id=0

### ISSUE THREAD

**Issue by zdila** [mongoose-os-libs/bt-common#10]
If I succesfully open a connection with periphery (`conn_id=0`) and then opening a connection to a different periphery fails, then mos closes connection 0.

The reason is that `ESP_GATTC_OPEN_EVT` probably only [sets `conn_id` if there is no error](https://github.com/espressif/esp-idf/blob/86c9b63546c2efee2a8ef43fca03c98dc38f6f6a/components/bt/bluedroid/bta/hh/bta_hh_le.c#L1394). Mos unfortunately uses `conn_id` and [closes it](https://github.com/mongoose-os-libs/bt-common/blob/79c0780090751bab39ad77e224f7cbb6e144d767/src/esp32/esp32_bt_gattc.c#L171). Maybe mos should just not try to close the connection for `ESP_GATTC_OPEN_EVT`.

**Comment by zdila** [comment]
Commenting that else branch could also fix #9.

**Comment by rojer** [comment]
i think your theory makes sense. i submitted a change, please test an let me know if it fixes this and #9 as well.

thanks!

**Comment by zdila** [comment]
Thanks. If fixes both issues. But there is still something:

* logs still mention `cid` and thus are misleading:

```
[Mar 12 20:23:43.795] W (165415) BT_APPL: bta_gattc_conn_cback() - cif=3 connected=0 conn_id=259 reason=0x0100
[Mar 12 20:23:43.804] esp32_bt_gatts.c:860    DISCONNECT cid 1 addr b4:e6:2d:b0:46:03
[Mar 12 20:23:43.810] esp32_bt_gattc.c:158    OPEN if 3 cid 0 addr b4:e6:2d:b0:46:03 st 0x85 mtu 0
```

* Regarding #9 `MGOS_BT_GATTC_EV_DISCONNECT` is also triggered twice on central if periphery shuts down when the connection was active. This was not actually the subject of #9 but it's a simmilar thing.

**Comment by rojer** [comment]
well, we just print whatever we get from above. cid _is_ 0, after all. it's just that when st is non-zero, it's meaningless. the point of these messages is to reflect what is being sent from IDF, so we should continue printing it.
